---
title: "Geog0162_Week3"
output: html_document
date: "2023-01-23"
---

```{r}
library(spatstat)
library(here)
library(sp)
library(rgeos)
library(maptools)
library(tmap)
library(sf)
library(geojson)
library(geojsonio)
library(tmaptools)
library(janitor)
library(spatialreg)
library(tidyverse)
library(readxl)
library(spdep)
library(plotly)
# load dependencies
library(biscale)
library(rstudioapi)
library(magrittr) # pipes
library(lintr) 
library(raster) 
library(viridis)
library(cowplot) 
```

```{r}
# Use read_sf() function to load shape file 
# Use read_sf() function to load shape file 
LSOAshp <- read_sf(here::here("Week3","London LSOA Areas.shp"))
BOROUGHshp <- read_sf(here::here("Week3","London Borough Areas.shp"))
# Generate an empty map to visualise the spatial configuration and hierarchy of LSOA and Boroughs
# First add LSOA layer 
# Generate an empty map to visualise the spatial configuration and hierarchy of LSOA and Boroughs
# First add LSOA layer 
tm_shape(LSOAshp) + tm_polygons() +
# Add Borough layer on top of LSOA layer and make it transparent with alpha = 0
tm_shape(BOROUGHshp) + tm_polygons(alpha = 0, border.alpha = 1, border.col = "black") +
# Apply cosmetics by adding compass and scale
tm_compass(position = c("right", "top")) + tm_scale_bar(position = c("left", "bottom"))
```

```{r}
# Use read.csv() to import 
datafile <- read.csv(here::here("Week3","London LSOA 2015 data.csv"))

# Merge datafile to LSOAshp uniquely by using "LSOACODE column
spatialdatafile <- merge(LSOAshp, datafile, by.x = "LSOACODE", by.y = "LSOACODE")
class(spatialdatafile)
data <- bi_class(spatialdatafile, x = AVEPRICE, y = AVEINCOME, style = "quantile", dim = 3)
```

```{r}
theme_map <- function(...) {
  theme_minimal() +
  theme(
    text = element_text(family = default_font_family,
                        color = default_font_color),
    # remove all axes
    axis.line = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    # add a subtle grid
    panel.grid.major = element_line(color = "#dbdbd9", size = 0.2),
    panel.grid.minor = element_blank(),
    # background colors
    plot.background = element_rect(fill = default_background_color,
                                   color = NA),
    panel.background = element_rect(fill = default_background_color,
                                    color = NA),
    legend.background = element_rect(fill = default_background_color,
                                     color = NA),
    # borders and margins
    plot.margin = unit(c(.5, .5, .2, .5), "cm"),
    panel.border = element_blank(),
    panel.spacing = unit(c(-.1, 0.2, .2, 0.2), "cm"),
    # titles
    legend.title = element_text(size = 11),
    legend.text = element_text(size = 9, hjust = 0,
                               color = default_font_color),
    plot.title = element_text(size = 15, hjust = 0.5,
                              color = default_font_color),
    plot.subtitle = element_text(size = 10, hjust = 0.5,
                                 color = default_font_color,
                                 margin = margin(b = -0.1,
                                                 t = -0.1,
                                                 l = 2,
                                                 unit = "cm"),
                                 debug = F),
    # captions
    plot.caption = element_text(size = 7,
                                hjust = .5,
                                margin = margin(t = 0.2,
                                                b = 0,
                                                unit = "cm"),
                                color = "#939184"),
    ...
  )
}
```

```{r}
plot1 <- tm_shape(spatialdatafile) + tm_fill("AVEPRICE", style = "quantile", n = 7, palette = "Greens") +
tm_shape(BOROUGHshp) + tm_polygons(alpha = 0, border.alpha = 1, border.col = "black") +
tm_text("BOROUGHN", size = "AREA") +
tm_compass(position = c("right", "top")) +
tm_scale_bar(position = c("left", "bottom")) +
tm_layout(frame = FALSE, legend.title.size = 0.5, legend.text.size = 0.5)

# plot the image object
plot1

```

```{r}
no_classes <- 6

quantiles <- spatialdatafile %>%
  pull(AVEINCOME) %>%
  quantile(probs = seq(0, 1, length.out = no_classes + 1)) %>%
  as.vector() # to remove names of quantiles, so idx below is numeric

labels <- imap_chr(quantiles, function(., idx){
  return(paste0(round(quantiles[idx] / 1000, 0),
                             "k",
                             " – ",
                             round(quantiles[idx + 1] / 1000, 0),
                             "k"))
})

labels <- labels[1:length(labels) - 1]


spatialdatafile %<>%
  mutate(AVEINCOME_quantiles = cut(AVEINCOME,
                               breaks = quantiles,
                               labels = labels,
                               include.lowest = T))


```


```{r}
# create 3 buckets for gini
quantiles_AVEPRICE <- spatialdatafile %>%
  pull(AVEPRICE) %>%
  quantile(probs = seq(0, 1, length.out = 4))

# create 3 buckets for mean income
quantiles_AVEINCOME <- spatialdatafile %>%
  pull(AVEINCOME) %>%
  quantile(probs = seq(0, 1, length.out = 4))

# create color scale that encodes two variables
# red for gini and blue for mean income
# the special notation with gather is due to readibility reasons
bivariate_color_scale <- tibble(
  "3 - 3" = "#3F2949", # high inequality, high income
  "2 - 3" = "#435786",
  "1 - 3" = "#4885C1", # low inequality, high income
  "3 - 2" = "#77324C",
  "2 - 2" = "#806A8A", # medium inequality, medium income
  "1 - 2" = "#89A1C8",
  "3 - 1" = "#AE3A4E", # high inequality, low income
  "2 - 1" = "#BC7C8F",
  "1 - 1" = "#CABED0" # low inequality, low income
) %>%
  gather("group", "fill")
```

```{r}
spatialdatafile %<>%
  mutate(
    AVEPRICE_quantiles = cut(
      AVEPRICE,
      breaks = quantiles_AVEPRICE,
      include.lowest = TRUE
    ),
    AVEINCOME_quantiles = cut(
      AVEINCOME,
      breaks = quantiles_AVEINCOME,
      include.lowest = TRUE
    ),
  
    # 在 tibble bivariate_color_scale 中
    group = paste(
      as.numeric(AVEPRICE_quantiles), "-",
      as.numeric(AVEINCOME_quantiles)
    )
  ) %>%
  left_join(bivariate_color_scale, by = "group")
```

```{r}
map <- ggplot() +
  geom_sf(data = data, mapping = aes(fill = bi_class), color = "white", size = 0.05, show.legend = FALSE) +
  bi_scale_fill(pal = "GrPink", dim = 3) +
  labs(
    title = "Social inequality in London",
    subtitle = "Average house prices and average incomes") +theme(
    subtitle.title = element_text(size = 2)
  )+
  bi_theme()
```

```{r}
# separate the groups
bivariate_color_scale %<>%
  separate(group, into = c("AVEPRICE", "AVEINCOME"), sep = " - ") %>%
  mutate(AVEPRICE = as.integer(AVEPRICE),
         AVEINCOME = as.integer(AVEINCOME))

legend <- ggplot() +
  geom_tile(
    data = bivariate_color_scale,
    mapping = aes(
      x = AVEPRICE,
      y = AVEINCOME,
      fill = fill)
  ) +
  scale_fill_identity() +
  labs(x = "Higher Housing Price ⟶️",
       y = "Higher income ⟶️") +
  theme_minimal() +
  # make font small enough
  theme(
    axis.title = element_text(size = 6)
  ) +
  # quadratic tiles
  coord_fixed()
```

```{r}
ggdraw() +
  draw_plot(map, 0, 0, 1, 1) +
  draw_plot(legend, 0.05, 0.075, 0.2, 0.2)
```

